ranmapg.height=8
ranmapg.width=8
ranmapg.treesn=4
ranmapg.tann=8
fmapgen.fpath=src/main/resources/level.txt

map.levelConfigFileName=level.tmx
map.tankTextureFile=images/tank_blue.png
map.treeTextureFile=images/greenTree.png
map.bulletTexture=images/bullet.png
